[package]
name = "ruax"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Xue Haonan <xuehaonan27@gmail.com>"]
description = "Lua interpreter implemented in Rust."
repository = "https://github.com/xuehaonan27/ruax"

[dependencies]
